const EFFECTIVE_DATE = "29 July 2025";

export default function Terms() {
  return (
    <div className="bg-background text-foreground">
      <section className="container py-16 md:py-24">
        <div className="mx-auto max-w-3xl space-y-6">
          <p className="text-sm uppercase tracking-wide text-muted-foreground">Terms of use</p>
          <h1 className="font-serif text-4xl md:text-5xl">Brieflee.be – Terms of Use</h1>
          <p className="text-sm text-muted-foreground">Effective date: {EFFECTIVE_DATE}</p>
          <p className="text-muted-foreground">
            These Terms of Use ("Terms") govern your access to and use of the Brieflee.be platform operated by BZ Trade BV. By creating an account or using the
            Service, you agree to be bound by these Terms. If you do not agree, do not access the Service. Questions? Email
            {" "}
            <a className="text-primary underline" href="mailto:support@brieflee.be">support@brieflee.be</a>.
          </p>
        </div>
      </section>

      <section className="container pb-24 md:pb-40">
        <div className="mx-auto max-w-3xl space-y-16 md:space-y-20">
          <article className="space-y-4">
            <h2 className="font-serif text-2xl">1. Acceptance of the Terms</h2>
            <p className="text-sm text-muted-foreground">
              By creating an account or using Brieflee.be, you accept these Terms. If you disagree with any provision, you must cease using the Service.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">2. Definitions</h2>
            <ul className="list-disc space-y-2 pl-6 text-sm text-muted-foreground">
              <li>
                <strong className="text-foreground">"Service"</strong> – the Brieflee.be web platform and related content delivered by BZ Trade BV.
              </li>
              <li>
                <strong className="text-foreground">"User Content"</strong> – any text, files, or data uploaded or generated by you within the Service.
              </li>
            </ul>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">3. Eligibility</h2>
            <p className="text-sm text-muted-foreground">
              You must be at least 16 years old and capable of entering into a binding contract. The Service is aimed at legal professionals; however, it does
              not constitute legal advice.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">4. Account Registration and Security</h2>
            <p className="text-sm text-muted-foreground">
              You agree to provide accurate information during registration and to keep your credentials confidential. You are responsible for all activities
              carried out under your account.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">5. Licence and Acceptable Use</h2>
            <p className="text-sm text-muted-foreground">
              We grant you a non-exclusive, revocable licence to access and use the Service for your professional or educational purposes. You must not:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-sm text-muted-foreground">
              <li>Use the Service to violate law or third-party rights.</li>
              <li>Scrape, reverse engineer, or circumvent security measures.</li>
              <li>Upload unlawful, infringing, or malicious content.</li>
            </ul>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">6. Subscription Plans and Payments</h2>
            <p className="text-sm text-muted-foreground">
              Brieflee.be offers a free tier and paid subscriptions. Paid plans are billed in advance and renew automatically unless cancelled. Prices exclude
              applicable VAT. You may cancel at any time; payments are non-refundable except where required by law.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">7. Intellectual Property</h2>
            <p className="text-sm text-muted-foreground">
              All software, interfaces, and content provided by BZ Trade remain our exclusive property. User Content remains yours, but you grant us a
              worldwide licence to host and display it solely to provide the Service.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">8. Third-Party Services</h2>
            <p className="text-sm text-muted-foreground">
              The Service may contain links to third-party websites. BZ Trade is not responsible for their content or availability.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">9. Disclaimer and Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground">
              The Service and all content are provided "as is" without warranty. We do not guarantee that outputs are complete, current, or fit for any
              particular purpose, and they do not constitute legal advice. To the maximum extent permitted by law, BZ Trade's aggregate liability arising out
              of or relating to the Service shall not exceed the total fees you paid to us in the 12 months preceding the claim.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">10. Termination</h2>
            <p className="text-sm text-muted-foreground">
              You may stop using the Service at any time. We may suspend or terminate your account with prior notice if you breach these Terms. Upon
              termination, Sections 7, 8, 9, and 11 survive.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">11. Governing Law and Jurisdiction</h2>
            <p className="text-sm text-muted-foreground">
              These Terms and any disputes are governed by Belgian law, with exclusive jurisdiction of the courts of Antwerp, Belgium.
            </p>
          </article>

          <article className="space-y-4">
            <h2 className="font-serif text-2xl">12. Changes to the Terms</h2>
            <p className="text-sm text-muted-foreground">
              We may update these Terms to reflect operational or legal changes. We will notify you at least 14 days before new Terms take effect. Continued
              use after the effective date constitutes acceptance.
            </p>
          </article>
        </div>
      </section>
    </div>
  );
}
